before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: WYiVt+ncC31XpLGpwjq/OgW3Nc7CPXdXuPUCOBQli3DphMHkyTCeq77B+9IBbgzSquuT4lkvT2TcqBs8VvhQDROKU1P16mDvC6C61zf++qghub/KZbLfI9ktekh0zV7DuINtB90Tj5xy0wyva5U7IuzerT5UbmXcXsXAh46TE68Kxdcb4xM3fujPup2CxZkyOQ9ttVU1sJ/HtsVVSIY/AA3CcSYxnqCqO9oWbsucigtiRGBasZi/tX41Qdse93c3otlisWHI2kQMeri9tPTP7G9KLJSzDOlkOKstzq3dRBq7/SDNr0XM1KSxcjreBfUCUL4QKEUmtSGsbSwh+eldfwmQ7y+lAsUkIki5VcwQAXdbYFFX8y9q3sYCQUgc0yXmPr4Pdwsq8D0rPjfvtzvgOK6zLyiVNyp5N/MuZ7lVwFqakiCfPq3euDlyr0ABB0PhZQtjF/xKxQRQksc/vb+GByEj0J3jc27rMsZtPn7z0K3fi7nehFMDan1lk0E8U8NcNHnj+qV5sWY93yDqq+1BqEWbCitbQ+nRa34UYTWtoiaeylXUcYawfP5/0MVtYH+zDfk1fzZycI7Udgmq0lwjTHjKoquvMSaFS1jPhf2PK5PnsQqctOSqPbvLEjsg4AYnCTICYb6CQhaTjr+eqRZFKQ7yJqJr/dgsn4boZvohP4E= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
